GET http://localhost:8787/api/aio
x-api-key: 77OtWlqXFt6iZ3+6kYgiQMt7YUAs7otLUfJj0qFpbM4=

### 
GET http://localhost:8787/api/admin/weread/session
x-api-key: 77OtWlqXFt6iZ3+6kYgiQMt7YUAs7otLUfJj0qFpbM4=

### 
POST http://localhost:8787/api/admin/weread/session
x-api-key: 77OtWlqXFt6iZ3+6kYgiQMt7YUAs7otLUfJj0qFpbM4=
Content-Type: application/json

{
    "vid": "449518091",
    "skey": "hhUskVpN"
}
